### ISSUE TITLE
StreamsBuilderS.globalTable misses overload with Consumed[K, V] as parameter

### ISSUE THREAD

**Issue by jeroenr** [lightbend/kafka-streams-scala#31]
First of all, thanks a lot for this library. It makes my code look much cleaner.

I did notice that ```StreamsBuilderS.globalTable``` has no overload where I can pass a customer ```Consumed[K, V]``` parameter as in 

```(new StreamsBuilderS).globalTable("my_table", Consumed.`with`(new MyKeySerde, new MyValueSerde))```

My current workaround is to use the ```inner``` StreamsBuilder like:

```(new StreamsBuilderS).inner.globalTable("my_table", Consumed.`with`(new MyKeySerde, new MyValueSerde))```

Is there any specific reason why ```StreamsBuilderS.globalTable``` doesn't have this overload?

**Comment by debasishg** [comment]
Glad to hear that it makes your code cleaner. Regarding `StreamsBuilderS.globalTable` we will add the overloads. No specific reason NOT to have them.

**Comment by debasishg** [comment]
Fixed on `develop` branch.
