### ISSUE TITLE
Is 2.11 supported?

### ISSUE THREAD

**Issue by rquinlivan** [lightbend/kafka-streams-scala#39]
I cannot seem to compile a simple application based on Confluent's example in Scala 2.11. Below is a sample of the code I am using. The compiler cannot make sense of the `flatMapValues` signature, with or without the implicit conversions. I am guessing that I am hitting an issue with the SAM translations from the Java 8 stream API. Does this library have some additional conversions that are meant to apply here? Is 2.11 supported?

```
    val statusUpdates: KStream[String, StatusUpdate] =
      builder.stream[String, StatusUpdate](Serdes.String(), CustomSerdes.statusUpdate, "statusUpdate")

    statusUpdates.
      flatMapValues(statusUpdate => statusUpdate.metrics.getOrElse(Seq.empty)).
      to(Serdes.String(), CustomSerdes.metric, "metrics")

    new KafkaStreams(builder, streamingConfig)

```

**Comment by debasishg** [comment]
Can you please point to the full example of Confluent ? The library supports Scala 2.11 and we have examples of working `flatMapValues` [here](https://github.com/lightbend/kafka-streams-scala/blob/develop/src/test/scala/com/lightbend/kafka/scala/streams/KafkaStreamsTest.scala#L55).

I can take a look at the error by trying out the example.

**Comment by rquinlivan** [comment]
@debasishg I forgot to call into `KafkaStreamS`, after fixing it it's working now. Thanks!
