### ISSUE TITLE
Mockedstreams for unit testing!

### ISSUE THREAD

**Issue by s3ni0r** [lightbend/kafka-streams-scala#50]
Hi,
I have been learning about Kafka streams lately using Scala, and came across this repo which is perfect 👍, i have seen that for testing (integration) you use an embedded Kafka which is a bit hard to set up for tests, would it be possible to integrate https://github.com/jpzk/mockedstreams which is based on Kafka's ProcessorTopologyTestDriver to avoid having zookeeper and Kafka brokers on each test?
this will enable developers to fiddle with Kafka streams in a lightweight manner.
Thanks!

**Comment by debasishg** [comment]
Mocking is an option for unit tests, but to be honest infrastructure stuff like Kafka needs some integration testing. Hence all the tests are full examples using embedded Kafka server. These are in reality not unit tests, but integration tests. If you look at Confluent's example repositories, they also do the same thing.

**Comment by s3ni0r** [comment]
Ok, i see your point, thanks for taking the time to answer.
