### ISSUE TITLE
kafka server utils not being packaged

### ISSUE THREAD

**Issue by Ir1sh** [lightbend/kafka-streams-scala#56]
Hi guys, the readme says you distribute the test utils in src/test with the library, particularly the local kafka server utils.  However it does not appear to be in my path and when I use the ARchive browser in sonatype I dont see the server package in any of releases.  Am I missing something or would this line https://github.com/lightbend/kafka-streams-scala/blob/develop/build.sbt#L57 prevent the test resources being shipped?

**Comment by debasishg** [comment]
Hi - I am traveling right now for a conference .. I will try to have this in place once I get some time. It’s true right now we don’t ship the utilities ..

**Comment by Ir1sh** [comment]
ok thanks a little copy pasting has me sorted for now anyway

**Comment by seglo** [comment]
@Ir1sh can you link to the part of the README that makes this mention?  I'm having trouble finding it.  We don't want to distribute the test library so if the README has conflicting info then we should reword it.

**Comment by Ir1sh** [comment]
sure https://github.com/lightbend/kafka-streams-scala#running-the-tests

> The library comes with an embedded Kafka server.

Maybe I am interpreting that line wrong.  

I think providing utils that allow you to easily test the streams you create with this library is the way to go instead of having to reimplement everything in `com.lightbend.kafka.scala.server`, if they don't notice it is there, or copy and pasting it, if they do.

The value of that vs the solution to `get sucked up and pollute downstream projects` (add excludes in your build.sbt is all it takes to solve that right?) seems more than worth it to me.  You could also publish a package with them and one without them if it really could cause a problem.

Either way, cool library thanks for the replies.

**Comment by seglo** [comment]
@Ir1sh My mistake, you're correct.  That's certainly something to consider.  /cc @debasishg

**Comment by debasishg** [comment]
Making `publishArtifact in Test := true` will allow publishing of `kafka-streams-scala_2.12-tests.jar`, which should be ok ..

**Comment by debasishg** [comment]
Fixed with `0.2.0`.
