### ISSUE TITLE
KStream-KTable inner join

### ISSUE THREAD

**Issue by nvladimiroff** [lightbend/kafka-streams-scala#64]
Is there a reason that `KSteamS#join` is a [left join](https://github.com/lightbend/kafka-streams-scala/blob/develop/src/main/scala/com/lightbend/kafka/scala/streams/KStreamS.scala#L140) instead of an inner join? Given that Kafka is pretty consistent that `join` is an inner join, I'm a little confused why kafka-streams-scala's `join` calls `leftJoin`.

**Comment by debasishg** [comment]
Thanks for pointing it out - it's a typo. Will fix it ..
