### ISSUE TITLE
Proposal to add Circe support

### ISSUE THREAD

**Issue by joan38** [lightbend/kafka-streams-scala#68]
Hi,

For the people using Circe with Kafka Streams I have created a little Serde adapter: https://github.com/joan38/kafka-streams-circe

This is way too tiny to be in a separate repo on it's own so I was thinking maybe it's a good idea to add this here in a separate project.

Something like:
- kafka-streams-core
- kafka-streams-circe
- docs (with sbt-microsite for example)
- (Any other stuff here?)

Just like in https://github.com/sksamuel/elastic4s
This may solve the questions around https://github.com/lightbend/kafka-streams-scala/issues/42

Let me know what you think. I'm more than happy to do the change.

Cheers

**Comment by joan38** [comment]
This is irrelevant now since this repo got merged in apache/kafka

**Comment by DevonPeroutky** [comment]
Is there a corresponding issue in apache/kafka? Is this still the only way to use circe with Kafka?

**Comment by joan38** [comment]
Hi @DevonPeroutky

I don't think apache/kafka would like to be circe specific. The easy way to use it is to depend on:
```
"com.goyeau" %% "kaka-streams-circe" % "0.5"
```
See https://github.com/joan38/kafka-streams-circe for more info.

**Comment by DevonPeroutky** [comment]
Yeah, that's what I ended up doing. Thanks for writing this. It's exactly what I needed!
