### ISSUE TITLE
stable URL to publish 'current' API documentation

### ISSUE THREAD

**Issue by raboof** [lightbend/kafka-streams-scala#77]
API documentation is now available at https://developer.lightbend.com/docs/api/kafka-streams-scala/0.2.1/com/lightbend/kafka/scala/streams/ , but that URL is tied to version 0.2.1. It would be nice to be able to point to https://developer.lightbend.com/docs/api/kafka-streams-scala/current/com/lightbend/kafka/scala/streams/

**Comment by deanwampler** [comment]
This should be deleted. This code is now part of Kafka Streams itself, so there's no reason to keep this content here. It's just confusing.

**Comment by raboof** [comment]
Cool, I didn't realize!
