### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by raboof** [lightbend/kafka-streams-scala#78]
Since it has been included upstream

https://github.blog/2017-11-08-archiving-repositories/

**Comment by deanwampler** [comment]
Good idea. @debasishg, @seglo, any reason we shouldn't archive this repo?

**Comment by deanwampler** [comment]
Good idea. @debasishg, @seglo, any reason we shouldn't archive this repo?

**Comment by seglo** [comment]
@deanwampler Can't think of one.

**Comment by deanwampler** [comment]
Okay. I'm going to archive it. It's easy enough to undo if we find the need...
